"""Generate the firmware's schema predicates from the frozen v1 schema.

Run with --check to detect schema/generated-code drift; no downloads.
"""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = json.loads((root / 'docs/development/sync/snapshot-v1.schema.json').read_text())
functions = []
seen = {}

def generate(s):
    key = json.dumps(s, sort_keys=True)
    if key in seen:
        return seen[key]
    name = 'schema' + str(len(seen))
    seen[key] = name
    lines = []
    if 'anyOf' in s:
        lines += ['return ' + ' || '.join(generate(x) + '(v)' for x in s['anyOf']) + ';']
    else:
        t = s.get('type')
        if t == 'object':
            predicates = {k: generate(v) for k, v in s['properties'].items()}
            lines += ['if (!v.is<JsonObjectConst>()) return false;', 'const auto object = v.as<JsonObjectConst>();']
            if 'minProperties' in s:
                lines += [f"if (object.size() < {s['minProperties']}) return false;"]
            for k in s.get('required', []):
                lines += [f'if (object[{json.dumps(k)}].isUnbound()) return false;']
            lines += ['for (JsonPairConst item : object) {', '  const char* key = item.key().c_str();']
            for i, (k, f) in enumerate(predicates.items()):
                lines += [f'  {"if" if i == 0 else "else if"} (std::strcmp(key, {json.dumps(k)}) == 0) {{ if (!{f}(item.value())) return false; }}']
            lines += ['  else return false;', '}', 'return true;']
        elif t == 'array':
            child = generate(s['items'])
            lines += ['if (!v.is<JsonArrayConst>()) return false;', f"if (v.size() > {s['maxItems']}) return false;", f'for (JsonVariantConst item : v.as<JsonArrayConst>()) if (!{child}(item)) return false;', 'return true;']
        elif t == 'integer':
            # Require integer representation; do not coerce booleans or floats.
            if s.get('minimum', 0) < 0:
                lines += ['if (!v.is<int64_t>()) return false;', f"if (v.as<int64_t>() < {s['minimum']} || v.as<int64_t>() > {s['maximum']}) return false;"]
            else:
                lines += ['if (!v.is<uint64_t>()) return false;']
                if 'minimum' in s:
                    lines += [f"if (v.as<uint64_t>() < {s['minimum']}ULL || v.as<uint64_t>() > {s['maximum']}ULL) return false;" if s['minimum'] else f"if (v.as<uint64_t>() > {s['maximum']}ULL) return false;"]
        elif t == 'number':
            lines += ['if (!v.is<double>()) return false;', f"if (!std::isfinite(v.as<double>()) || v.as<double>() < {s['minimum']} || v.as<double>() > {s['maximum']}) return false;"]
        elif t == 'boolean':
            lines += ['if (!v.is<bool>()) return false;']
        elif t == 'null':
            lines += ['if (!v.isNull()) return false;']
        elif t == 'string':
            lines += ['if (!v.is<const char*>()) return false;']
            if 'maxLength' in s:
                lines += [f"if (unicodeLength(v.as<JsonString>()) > {s['maxLength']}) return false;"]
            if s.get('pattern', '').startswith('^[0-9a-f]'):
                lines += ['if (!validBookId(v.as<JsonString>())) return false;']
        if 'const' in s:
            value = s['const']
            lines += [f'if (v != {json.dumps(value)}) return false;']
        if 'enum' in s:
            lines += ['if (!v.is<const char*>()) return false;', 'if (' + ' && '.join('v != ' + json.dumps(x) for x in s['enum']) + ') return false;']
        if 'not' in s:
            lines += ['if (v == ' + json.dumps(s['not']['const']) + ') return false;']
        if t not in ('object', 'array'):
            lines += ['return true;']
    functions.append('bool ' + name + '(JsonVariantConst v) {\n  ' + '\n  '.join(lines) + '\n}\n')
    return name

entry = generate(schema)
text = '// Generated by test/generate_snapshot_validator.py; do not edit.\n// clang-format off\n' + '\n'.join(functions) + '\nbool validateSchema(JsonVariantConst v) { return ' + entry + '(v); }\n// clang-format on\n'
path = root / 'src/sync/SnapshotSchema.generated.h'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
if args.check:
    assert path.read_text() == text, 'Regenerate snapshot schema validator'
else:
    path.write_text(text)
