// Generated by test/generate_snapshot_validator.py; do not edit.
// clang-format off
bool schema1(JsonVariantConst v) {
  if (v != "yomuka-book-snapshot") return false;
  return true;
}

bool schema2(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v != 1) return false;
  return true;
}

bool schema3(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (!validBookId(v.as<JsonString>())) return false;
  if (v == "0000000000000000") return false;
  return true;
}

bool schema4(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() > 4294967295ULL) return false;
  return true;
}

bool schema8(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() > 65535ULL) return false;
  return true;
}

bool schema10(JsonVariantConst v) {
  if (!v.isNull()) return false;
  return true;
}

bool schema9(JsonVariantConst v) {
  return schema8(v) || schema10(v);
}

bool schema12(JsonVariantConst v) {
  if (!v.is<bool>()) return false;
  return true;
}

bool schema11(JsonVariantConst v) {
  return schema12(v) || schema10(v);
}

bool schema14(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() > 100ULL) return false;
  return true;
}

bool schema13(JsonVariantConst v) {
  return schema14(v) || schema10(v);
}

bool schema7(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["spineIndex"].isUnbound()) return false;
  if (object["chapterPage"].isUnbound()) return false;
  if (object["chapterPageCount"].isUnbound()) return false;
  if (object["finished"].isUnbound()) return false;
  if (object["percent"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "spineIndex") == 0) { if (!schema8(item.value())) return false; }
    else if (std::strcmp(key, "chapterPage") == 0) { if (!schema8(item.value())) return false; }
    else if (std::strcmp(key, "chapterPageCount") == 0) { if (!schema9(item.value())) return false; }
    else if (std::strcmp(key, "finished") == 0) { if (!schema11(item.value())) return false; }
    else if (std::strcmp(key, "percent") == 0) { if (!schema13(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema6(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["updatedAt"].isUnbound()) return false;
  if (object["data"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "updatedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "data") == 0) { if (!schema7(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema18(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() < 1ULL || v.as<uint64_t>() > 65535ULL) return false;
  return true;
}

bool schema19(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (unicodeLength(v.as<JsonString>()) > 512) return false;
  return true;
}

bool schema20(JsonVariantConst v) {
  if (!v.is<double>()) return false;
  if (!std::isfinite(v.as<double>()) || v.as<double>() < 0 || v.as<double>() > 1) return false;
  return true;
}

bool schema17(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["spineIndex"].isUnbound()) return false;
  if (object["chapterPage"].isUnbound()) return false;
  if (object["chapterPageCount"].isUnbound()) return false;
  if (object["summary"].isUnbound()) return false;
  if (object["progressRatio"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "spineIndex") == 0) { if (!schema8(item.value())) return false; }
    else if (std::strcmp(key, "chapterPage") == 0) { if (!schema8(item.value())) return false; }
    else if (std::strcmp(key, "chapterPageCount") == 0) { if (!schema18(item.value())) return false; }
    else if (std::strcmp(key, "summary") == 0) { if (!schema19(item.value())) return false; }
    else if (std::strcmp(key, "progressRatio") == 0) { if (!schema20(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema16(JsonVariantConst v) {
  if (!v.is<JsonArrayConst>()) return false;
  if (v.size() > 24) return false;
  for (JsonVariantConst item : v.as<JsonArrayConst>()) if (!schema17(item)) return false;
  return true;
}

bool schema15(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["updatedAt"].isUnbound()) return false;
  if (object["data"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "updatedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "data") == 0) { if (!schema16(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema25(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "noto-serif" && v != "noto-sans" && v != "open-dyslexic") return false;
  return true;
}

bool schema26(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (unicodeLength(v.as<JsonString>()) > 31) return false;
  return true;
}

bool schema24(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["family"].isUnbound()) return false;
  if (object["sdFamilyName"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "family") == 0) { if (!schema25(item.value())) return false; }
    else if (std::strcmp(key, "sdFamilyName") == 0) { if (!schema26(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema27(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "small" && v != "medium" && v != "large" && v != "extra-large") return false;
  return true;
}

bool schema28(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() < 80ULL || v.as<uint64_t>() > 220ULL) return false;
  return true;
}

bool schema29(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() > 50ULL) return false;
  return true;
}

bool schema30(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "justified" && v != "left" && v != "center" && v != "right") return false;
  return true;
}

bool schema31(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() > 4ULL) return false;
  return true;
}

bool schema32(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() < 5ULL || v.as<uint64_t>() > 40ULL) return false;
  return true;
}

bool schema33(JsonVariantConst v) {
  if (!v.is<int64_t>()) return false;
  if (v.as<int64_t>() < -16 || v.as<int64_t>() > 64) return false;
  return true;
}

bool schema34(JsonVariantConst v) {
  if (!v.is<uint64_t>()) return false;
  if (v.as<uint64_t>() < 2ULL || v.as<uint64_t>() > 3ULL) return false;
  return true;
}

bool schema23(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "font") == 0) { if (!schema24(item.value())) return false; }
    else if (std::strcmp(key, "fontSize") == 0) { if (!schema27(item.value())) return false; }
    else if (std::strcmp(key, "lineSpacing") == 0) { if (!schema28(item.value())) return false; }
    else if (std::strcmp(key, "charSpacing") == 0) { if (!schema29(item.value())) return false; }
    else if (std::strcmp(key, "paragraphAlignment") == 0) { if (!schema30(item.value())) return false; }
    else if (std::strcmp(key, "extraParagraphSpacing") == 0) { if (!schema31(item.value())) return false; }
    else if (std::strcmp(key, "screenMargin") == 0) { if (!schema32(item.value())) return false; }
    else if (std::strcmp(key, "firstLineIndent") == 0) { if (!schema12(item.value())) return false; }
    else if (std::strcmp(key, "rubyEnabled") == 0) { if (!schema12(item.value())) return false; }
    else if (std::strcmp(key, "rubyOffsetX") == 0) { if (!schema33(item.value())) return false; }
    else if (std::strcmp(key, "rubyOffsetY") == 0) { if (!schema33(item.value())) return false; }
    else if (std::strcmp(key, "tateChuYokoMaxDigits") == 0) { if (!schema34(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema35(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "auto" && v != "horizontal" && v != "vertical") return false;
  return true;
}

bool schema36(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "portrait" && v != "landscape-cw" && v != "inverted" && v != "landscape-ccw") return false;
  return true;
}

bool schema37(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "crosspoint" && v != "epub" && v != "balanced") return false;
  return true;
}

bool schema38(JsonVariantConst v) {
  if (!v.is<const char*>()) return false;
  if (v != "display" && v != "placeholder" && v != "suppress") return false;
  return true;
}

bool schema22(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "horizontal") == 0) { if (!schema23(item.value())) return false; }
    else if (std::strcmp(key, "vertical") == 0) { if (!schema23(item.value())) return false; }
    else if (std::strcmp(key, "writingMode") == 0) { if (!schema35(item.value())) return false; }
    else if (std::strcmp(key, "orientation") == 0) { if (!schema36(item.value())) return false; }
    else if (std::strcmp(key, "bookStyle") == 0) { if (!schema37(item.value())) return false; }
    else if (std::strcmp(key, "imageRendering") == 0) { if (!schema38(item.value())) return false; }
    else if (std::strcmp(key, "invertImages") == 0) { if (!schema12(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema21(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["updatedAt"].isUnbound()) return false;
  if (object["data"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "updatedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "data") == 0) { if (!schema22(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema40(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["seconds"].isUnbound()) return false;
  if (object["sessionCount"].isUnbound()) return false;
  if (object["lastReadAt"].isUnbound()) return false;
  if (object["finishedAt"].isUnbound()) return false;
  if (object["finished"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "seconds") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "sessionCount") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "lastReadAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "finishedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "finished") == 0) { if (!schema12(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema39(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["updatedAt"].isUnbound()) return false;
  if (object["data"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "updatedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "data") == 0) { if (!schema40(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema5(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object.size() < 1) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "progress") == 0) { if (!schema6(item.value())) return false; }
    else if (std::strcmp(key, "bookmarks") == 0) { if (!schema15(item.value())) return false; }
    else if (std::strcmp(key, "readerSettings") == 0) { if (!schema21(item.value())) return false; }
    else if (std::strcmp(key, "history") == 0) { if (!schema39(item.value())) return false; }
    else return false;
  }
  return true;
}

bool schema0(JsonVariantConst v) {
  if (!v.is<JsonObjectConst>()) return false;
  const auto object = v.as<JsonObjectConst>();
  if (object["format"].isUnbound()) return false;
  if (object["formatVersion"].isUnbound()) return false;
  if (object["bookId"].isUnbound()) return false;
  if (object["exportedAt"].isUnbound()) return false;
  if (object["units"].isUnbound()) return false;
  for (JsonPairConst item : object) {
    const char* key = item.key().c_str();
    if (std::strcmp(key, "format") == 0) { if (!schema1(item.value())) return false; }
    else if (std::strcmp(key, "formatVersion") == 0) { if (!schema2(item.value())) return false; }
    else if (std::strcmp(key, "bookId") == 0) { if (!schema3(item.value())) return false; }
    else if (std::strcmp(key, "exportedAt") == 0) { if (!schema4(item.value())) return false; }
    else if (std::strcmp(key, "units") == 0) { if (!schema5(item.value())) return false; }
    else return false;
  }
  return true;
}

bool validateSchema(JsonVariantConst v) { return schema0(v); }
// clang-format on
