#!/usr/bin/env python3
"""Generate the CP932 two-byte to Unicode lookup table used by the TXT reader."""
from pathlib import Path

out = Path(__file__).resolve().parents[1] / "lib" / "Txt" / "Cp932Table.generated.h"
entries = []
for lead in list(range(0x81, 0xA0)) + list(range(0xE0, 0xFD)):
    for trail in list(range(0x40, 0x7F)) + list(range(0x80, 0xFD)):
        raw = bytes((lead, trail))
        try:
            value = raw.decode("cp932")
        except UnicodeDecodeError:
            continue
        if len(value) == 1 and ord(value) <= 0xFFFF:
            entries.append(((lead << 8) | trail, ord(value)))

with out.open("w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by scripts/gen_cp932_table.py; do not edit.\n#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n")
    f.write("struct Cp932Entry { uint16_t sjis; uint16_t unicode; };\n")
    f.write("static constexpr Cp932Entry kCp932Table[] = {\n")
    for sjis, unicode in entries:
        f.write(f"  {{0x{sjis:04X}, 0x{unicode:04X}}},\n")
    f.write("};\n")
    f.write("static constexpr size_t kCp932TableSize = sizeof(kCp932Table) / sizeof(kCp932Table[0]);\n")
